### ISSUE TITLE
Emotion error when integrating with Unify-react-desktop

### ISSUE THREAD

**Issue by regalius** [tokopedia/treats#5]
**Describe the bug**
When ~~importing unify-react-desktop~~ rendering react-emotion styled components, client-side renders caused cryptic error

Update: Apparently, this is issue with react-emotion 9.2.12 when trying to do SSR + Code split.

**Version**
0.1.0-alpha

**To Reproduce**
1. ~~import component from `unify-react-desktop`~~ Create styled component using react-emotion 9.2.12 (e.g. const Intro = styled.div\`...\`)
2. Render it in `welcome.js` or another component with code splitting (`AsyncLoader`)
3. `yarn start`
4. See error in console.log

**Expected behavior**
No error shown

**Screenshots**
![screen shot 2018-12-11 at 3 58 54 pm](https://user-images.githubusercontent.com/6160832/49789095-afeb0100-fd5d-11e8-8703-ff4bb2099172.png)

**Comment by miqdadfwz** [comment]
Not sure enough but I will work around for this

**Comment by martinock** [comment]
Hello @miqdadfwz and everyone who are checking this issue as well, before you start I have update on this issue, sorry for the delay on this update:

**Describe the bug:**
I already tried with `unify-react-desktop` and there's no issue. Apparently, this is issue with `react-emotion` 9.2.12. The issue happen when we try to SSR (Treats `client.js` `hydrate` make this error, changing it to `render` removing the issue, but this workaround is not what we are hoping for) and Code split (removing AsyncLoader on component `index.js` will remove this issue, once again, this is not what we hoping for)

**Version:**
0.1.0-alpha

**To Reproduce:**
1. Install react-emotion 9.2.12
2. Create styled component (e.g const Intro = styled.div\`....\`)
3. Render it in `welcome.js` (which is already code splitted)

**Expected behaviour:**
No error shown even when we are doing SSR + Code split

**Screenshots (still same)**

**Comment by martinock** [comment]
"emotion": "9.2.12",
"emotion-server": "9.2.12",
"react-emotion": "9.2.12"

These are dependencies related to current react emotion. To setup Treats with emotion, you may also want to look at our example [here](https://github.com/tokopedia/treats/tree/master/example/emotion-css)

**Comment by miqdadfwz** [comment]
Hi @martinochk well I have tried to install the issued dependencies to [the example folder](https://github.com/tokopedia/treats/tree/master/example/emotion-css) as well as to my own folder installed through `create-treats-app`. I also have copied all the code from `/example/emotion-css/src/page/welcome/welcome.js` to my own `welcome.js`. Strangely, the error occurs when only I used the example. Is it something missing? I mean like in my own starter there is no `_server` by default.

**Comment by martinock** [comment]
By default `_server` is not provided. `_server` is our filesystem hooks which we provided for developers, so developers can customise server behaviour, learn more at [docs](https://tokopedia.github.io/treats/docs/main-concept/custom-server-app.html). We need to use the emotion-server `renderStyleToString` method, so we can tell our server to render the styled component.

This issue happens when we try to SSR + Code split emotion component

**Comment by regalius** [comment]
Hmm, sorry been busy in other things and wasn't able to debug this issue.

I might've found the root cause for this issue, my suspect is with how emotion hydrate their SSR'ed markup, AFAIK, in `renderStylesToString` they inline each component's style in the markup itself and when hydrating the SSR'ed markup, they hoist all the style tags on `head` part of the DOM.

I think this causes:
1. mismatch in React's hydrate method
2. Race condition between React's hydrate and Emotion's trying to remove the style tag in the body

Skimmed Emotion's documentation a little bit and found out [a way to disable Emotion's speedy mode](https://5bb1495273f2cf57a2cf39cc--emotion.netlify.com/docs/ssr#puppeteer):
```
import { sheet } from 'emotion'
sheet.speedy(false)
```

Tried to apply this on `/src/_client/index.js` filesystem hooks and the errors are gone. Cheers!

**Comment by regalius** [comment]
Seems like this issue had been fixed, closing for now, will re-open when the same problem occurs 🎉
